[package]
name = "old-salsa"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
criterion = "0.5.1"
dashmap = "6.0.1"
salsa = { package = "salsa", version = "0.16" }

[[bench]]
name = "compare"
harness = false